Update dockerfile env syntax
Fixes this error:

```
------

 1 warning found (use docker --debug to expand):
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 3)
Dockerfile:10
--------------------
   8 |
   9 |     COPY package*.json ./
  10 | >>> RUN npm install
  11 |
--------------------
ERROR: failed to solve: process "/bin/sh -c npm install" did not complete successfully: exit code: 1
```